#XELLCONFIG

# General XeLL options
; netconfig - only if the ip= is valid and isnt the same as eventually in the previously parsed kboot.conf, the netconfig gets set
; if netconfig values aren't set/set invalid/commented, XeLL will use: Either supplied DHCP address or if no DHCP available, static IP (192.168.1.99/255.255.255.0)
ip=192.168.1.98
netmask=255.255.255.0
gateway=192.168.1.1

; tftp_enabled=1
; set custom tftp server IP
; incase no tftp_server= is set/set invalid/commented, XeLL will use: Supplied address via DHCP, if no DHCP available it will use 192.168.1.98
tftp_server=192.168.1.99

; XeLL's videomode - valid modes:
;  0: VIDEO_MODE_VGA_640x480
;  1: VIDEO_MODE_VGA_1024x768
;  2: VIDEO_MODE_PAL60
;  3: VIDEO_MODE_YUV_480P
;  4: VIDEO_MODE_PAL50
;  5: VIDEO_MODE_VGA_1280x768
;  6: VIDEO_MODE_VGA_1360x768
;  7: VIDEO_MODE_VGA_1280x720
;  8: VIDEO_MODE_VGA_1440x900
;  9: VIDEO_MODE_VGA_1280x1024
; 10: VIDEO_MODE_HDMI_720P
; 11: VIDEO_MODE_YUV_720P
; 12: VIDEO_MODE_NTSC
; If no value is set/set invalid/commented, XeLL will continue using the autodetected value
videomode=10

; speed up cpu - valid modes:
; 1: XENON_SPEED_FULL
; 2: XENON_SPEED_3_2
; 3: XENON_SPEED_1_2
; 4: XENON_SPEED_1_3
; If no value is set/set invalid/commented, XeLL won't change CPU Speed
speedup=1
